<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TabularDb.Core\TabularDb.Core.csproj" />
    <ProjectReference Include="..\TabularDb.Storage\TabularDb.Storage.csproj" />
  </ItemGroup>

</Project>
